# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SafeFood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafeFood
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'SVProgressHUD'
  pod 'STPopup'
  pod 'ImageSlideshow/Kingfisher'
  pod 'ReachabilitySwift'
  pod 'Moya', '~> 15.0'
  pod 'TTTAttributedLabel'
  pod 'AppAuth'
  pod 'FBSDKLoginKit', '~> 12.3.2'
  pod 'FBSDKShareKit', '~> 12.3.2'
  pod 'Toaster'
  pod 'FSPagerView'
  pod 'HCSStarRatingView', '~> 1.5'
  pod 'EmptyDataSet-Swift', '~> 5.0.0'
  pod 'FloatingPanel'
  pod 'YPImagePicker'
  pod 'ExpandableLabel'
  pod 'SVPullToRefresh'

  # Quality + Generation
  pod 'R.swift'
  
end
