# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SafeFood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafeFood
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'SVProgressHUD'
  pod 'STPopup'
  pod 'ImageSlideshow/Kingfisher'
  pod 'ReachabilitySwift'
  pod 'Moya', '~> 15.0'
  pod 'TTTAttributedLabel'
  pod 'AppAuth'
  pod 'FBSDKLoginKit', '~> 12.3.2'
  pod 'FBSDKShareKit', '~> 12.3.2'
  pod 'Toaster'
  pod 'FSPagerView'
  pod 'HCSStarRatingView', '~> 1.5'
  pod 'EmptyDataSet-Swift', '~> 5.0.0'
  pod 'FloatingPanel'
  pod 'YPImagePicker'
  pod 'ExpandableLabel'
  pod 'SVPullToRefresh'

  # Quality + Generation
  pod 'R.swift'
  
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end